//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Forging
    {
        public const string BundleName = "forging";
        public const string UI_DECOMPOSITION_MASTER = "ui_decomposition_master";
        public const string UI_EQU_MASTER = "ui_equ_master";
        public const string UI_MASTEROFFURNITURE = "ui_masteroffurniture";
        public const string UI_SMELTER = "ui_smelter";
        public const string UI_SMELTER_FAILURE = "ui_smelter_failure";
    }
    public class Game
    {
        public const string BundleName = "game";
        public const string GAME_SCENE_MAP_01 = "game_scene_map_01";
        public const string GAME_SCENE_MAP_02 = "game_scene_map_02";
        public const string GAME_SCENE_ROOM = "game_scene_room";
        public const string GAME_SCENE_ROOM_GROUD = "game_scene_room_groud";
        public const string GAME_SCENE_ROOM_GROUD_01 = "game_scene_room_groud_01";
        public const string GAME_SCENE_ROOM_GROUD_01_01 = "game_scene_room_groud_01_01";
        public const string GAME_SCENE_ROOM_GROUD_02 = "game_scene_room_groud_02";
        public const string GAME_SCENE_ROOM_GROUD_04 = "game_scene_room_groud_04";
        public const string GAME_SCENE_ROOM_GROUD_05 = "game_scene_room_groud_05";
        public const string GAME_SCENE_ROOM_GROUD_LIGHT = "game_scene_room_groud_light";
        public const string SCENE_ENTER_01 = "scene_enter_01";
        public const string SCENE_ENTER_02 = "scene_enter_02";
        public const string SCENE_ENTER_03 = "scene_enter_03";
        public const string SCENE_ENTER_04 = "scene_enter_04";
        public const string SCENE_ENTER_05 = "scene_enter_05";
        public const string U_MAPI_LEVEL_SCHEDULE_01 = "u_mapi_level_schedule_01";
        public const string U_MAPI_LEVEL_SCHEDULE_02 = "u_mapi_level_schedule_02";
        public const string U_MAPI_LEVEL_SCHEDULE_03 = "u_mapi_level_schedule_03";
        public const string UI_GAMEING_MAP_BAR = "ui_gameing_map_bar";
        public const string UI_GAMEING_MAP_BLESS = "ui_gameing_map_bless";
        public const string UI_GAMEING_MAP_BOOK = "ui_gameing_map_book";
        public const string UI_GAMEING_MAP_BOSS = "ui_gameing_map_boss";
        public const string UI_GAMEING_MAP_BOX = "ui_gameing_map_box";
        public const string UI_GAMEING_MAP_EQUIPMENT = "ui_gameing_map_equipment";
        public const string UI_GAMEING_MAP_FRAME = "ui_gameing_map_frame";
        public const string UI_GAMEING_MAP_MONSTER = "ui_gameing_map_monster";
        public const string UI_GAMEING_MAP_PUB = "ui_gameing_map_pub";
        public const string UI_GAMEING_MAP_REST = "ui_gameing_map_rest";
        public const string UI_GAMEING_MAP_ROOM_BLESS = "ui_gameing_map_room_bless";
        public const string UI_GAMEING_MAP_ROOM_BOSS = "ui_gameing_map_room_boss";
        public const string UI_GAMEING_MAP_ROOM_BOX = "ui_gameing_map_room_box";
        public const string UI_GAMEING_MAP_ROOM_EQUIPMENT = "ui_gameing_map_room_equipment";
        public const string UI_GAMEING_MAP_ROOM_MONSTER = "ui_gameing_map_room_monster";
        public const string UI_GAMEING_MAP_ROOM_PUB = "ui_gameing_map_room_pub";
        public const string UI_GAMEING_MAP_ROOM_REST = "ui_gameing_map_room_rest";
        public const string UI_GAMEING_MAP_ROOM_WITCH = "ui_gameing_map_room_witch";
        public const string UI_GAMEING_MAP_WITCH = "ui_gameing_map_witch";
    }
    public class Send
    {
        public const string BundleName = "send";
        public const string UI_SEND_NAME = "ui_send_name";
        public const string UI_SEND_RETURN = "ui_send_return";
        public const string UI_SEND_SCENE = "ui_send_scene";
        public const string UI_SEND_SCENE_01 = "ui_send_scene_01";
        public const string UI_SEND_SCENE_02 = "ui_send_scene_02";
        public const string UI_SEND_SCENE_03 = "ui_send_scene_03";
        public const string UI_SEND_SCENE_04 = "ui_send_scene_04";
        public const string UI_SEND_SCENE_05 = "ui_send_scene_05";
        public const string UI_SEND_SCENE_06 = "ui_send_scene_06";
        public const string UI_SEND_SCENE_07 = "ui_send_scene_07";
        public const string UI_SEND_SCENE_08 = "ui_send_scene_08";
        public const string UI_SEND_SCENE_09 = "ui_send_scene_09";
        public const string UI_SEND_SCENE_10 = "ui_send_scene_10";
        public const string UI_SEND_TREASUREHUNT_01 = "ui_send_treasurehunt_01";
        public const string UI_SEND_TREASUREHUNT_02 = "ui_send_treasurehunt_02";
        public const string UI_SEND_TREASUREHUNT_03 = "ui_send_treasurehunt_03";
    }
    public class Uiroot_prefab
    {
        public const string BundleName = "uiroot_prefab";
        public const string UIROOT = "uiroot";
    }
}
